### ISSUE TITLE
Solutions for the rest of the exercises?

### ISSUE THREAD

**Issue by Laumak** [FastDevCo/react-intro#6]
Hey,

If I remember correctly Teemu said that he would release the solutions for the rest of the exercises later. Are the solutions still going to be released or are we on our own from now on?

**Comment by elnygren** [comment]
@Laumak this is probably late to the party, but we are updating the course material with ES6 goodies and making sure we have solutions for each of the tasks.

Also working on some API stuff etc. coming soon and bringing this course to more people!

**Comment by theikkila** [comment]
And here we go:
https://github.com/FastDevCo/react-intro/pull/8
